---
title: "Understanding the Research Process"
author: "Dr Austin R Brown"
institute: "Kennesaw State University"
format: beamer
---

## Introduction

- When we hear the word "science," we probably think of people in lab coats surrounded by beakers and test tubes performing experiments of some kind.
    - Some of you may have done this type of work!
    
\vskip 0.10 in

- But we can define science much more broadly.
    - Science can be generally defined as a \textit{\underline{systematic}} and \textit{\underline{organized}} way of acquiring knowledge about the natural world, its phenomena, and the principles governing those phenomena.
    
## Introduction to the Scientific Method

- Part of the systematic and organized way we go about performing science is laid out for us by the scientific method (yes that same scientific method from high school science class).

\vskip 0.10 in

- The steps in the scientific method are:
    1. Observation
    2. Question
    3. Hypothesis
    4. Experiment
    5. Data Analysis
    6. Conclusion
    7. Communication
    
\vskip 0.10 in

- Let's consider a scenario and walk through each of these steps together!

## Observation: Research Scenario

- I am old enough to remember a time before social media. When it came into prominence when I was late in high school and early in college, I couldn't have imagined what it would grow into in such a short amount of time. It is amazing to me how easy it is to connect and share knowledge with people all over the world. Of course, there are problems with social media becoming so intertwined with our lives. I have especially noticed (or observed) people I know who spend lots of time on apps like Instagram exhibiting depressive symptoms. So that led me to wonder if the amount of time people spend on social media is associated with or related to depressive symptoms. 

## Question: Formulating the Research Question

- So I have observed something in the world that I'm interested in studying further. This is a great first step! Now, the next step is to formulate the research question.

\vskip 0.10 in

- The research question is key to the scientific method because it lays out the "roadmap" of our study including:
    - The specific group or groups we are interested in studying, which I call the \textit{\underline{Population(s) of Interest}} (the "who")
    - The specific qualities (i.e., variables) about the group or groups we are interested in studying further, which I call the \textit{\underline{Variable(s) of Interest}} (the "what")
    - The quantitative summary characteristic of the variables we are specifically interested in studying further (e.g., mean, median, proportion, slope, etc.), which I refer to as the \textit{\underline{Characteristic of the Variable to be Analyzed}} (more of the "what")
    - The \textit{\underline{General Analytical Method}} we will be using to perform the analysis (e.g., comparison, association) (touches on the "why")

## Question: Formulating the Research Question

- It is of critical importance to do this at the onset of the study, before data has been collected to ensure that we are getting the right data to answer our question!

\vskip 0.10 in

- So in our case, what would the elements of our research question specifically include? We have decisions to make!

## Question: Formulating the Research Question

- \textbf{\underline{Population of Interest:}} Suppose I'm specifically interested in University of Georgia undergraduate students. This is my population or group that I'm going to be collecting data from.

\vskip 0.10 in

- \textbf{\underline{Variables of Interest:}} Here I have two variables which I need to more clearly define: time spent on social media and depressive symptoms.

\vskip 0.10 in

- Let's pivot for a moment to talk more about the important topic of variables.

## Variables

- First of all, we have all heard the term "variable" in a math setting, but what does it mean in a scientific setting?

\vskip 0.10 in 

- In science, a \textbf{\underline{variable}} is some characteristic of something.
    - Hair color is a variable
    - Number of minutes per week spent on TikTok is a variable
    - Monthly amount of money spent on Dunkin coffee is a variable
    
## Variables

- Okay, so we can see that variables can be further classified into more specific types of variables.

\vskip 0.10 in

- A variable which is inherently measured by numbers is called a \textbf{\underline{quantitative}} variable.
    - Number of minutes per week on TikTok and monthly amount of money spent of Dunkin coffee are both examples of quantitative variables.
    
\vskip 0.10 in

- A variable which cannot be inherently be measured by numbers (like hair color) is called a \textbf{\underline{categorical}} or \textbf{\underline{qualitative}} variable.
    - Customer response surveys which ask us questions like "How satisfied were you with your Dunkin coffee on a scale from 1 - 5 with 1 meaning totally dissatisfied and 5 meaning totally satisfied?" are also categorical variables because the numbers are representing the customer's qualitative opinion!
    
## Variables

- We can even further differentiate between quantitative variables.

\vskip 0.10 in

- If a fraction makes sense for a quantitative variable, then we call this a \textbf{\underline{continuous}} quantitative variable
    - Number of ounces in a can of Coke
    - Amount of time it takes to commute to campus
    - Temperature on the surface of the Sun
    
\vskip 0.10 in

- If a fraction does not make sense for a quantitative variable, then we call this a \textbf{\underline{discrete}} quantitative variable
    - Number of Coke cans in my fridge
    - Number of undergraduate students enrolled at KSU
    - Number of free throws Trae Young makes this year
    
## Question: Formulating the Research Question

- Okay so circling back to the research question, we have two variables which we need to better define.

\vskip 0.10 in

- Maybe I can measure social media time by asking the UGA undergraduate students to show me their daily average usage of their top social media applicaiton (mine is suprisingly Instagram!). So our variable is not just social media usage, but it is specifically daily average amount of time spent on the most used social media application.
    - This is an example of a quantitative, continuous variable.
    
## Question: Formulating the Research Question

- What about depression? Typically, depression is measured using rigorously tested surveys developed by psychologists. Once a person fills out a survey, their responses are summed into one total numeric score with greater values generally denoting more severe depressive symptoms and vice versa. 
    - So suppose we choose a survey we want to give to the UGA undergraduate students. At the conclusion of the survey, we will end up with a quantitative score. So the variable "Depression Severity" is also a quantitative variable, but most likely a discrete quantitative variable.
    
## Question: Formulating the Research Question

- Next, we want to specify the characteristic to be analyzed. Here, what I'm truly most interested in is determining if there exists an association between social media usage and depression. Thus:

\vskip 0.10 in

- \textbf{\underline{Characteristic to be Analyzed:}} Correlation (we'll talk more about this later in the semester)

\vskip 0.10 in

- \textbf{\underline{General Analytical Method:}} Association

## Question: Formulating the Research Question

- Putting it all together:

\vskip 0.10 in

"Is there evidence that an association may exist between average amount of time spent on social media per day and depressive symptoms among University of Georgia undergraduate students?"

